### ISSUE TITLE
How to use fonts

### ISSUE THREAD

**Issue by rajam1215** [Binary-Finery/EZDialog#3]
@Binary-Finery 

how to use font in **.setFont()** method in your library

thanks

**Comment by rajam1215** [comment]
@Binary-Finery 
you don't give any answer with that type of stuff, your library not go in right direction.

**Comment by Binary-Finery** [comment]
Hi,

Sorry for the late reply, I've been extremely busy.

You can set any of the three bundled fonts via the Font enum class, for example:

.setFont(Font.COMFORTAA)


All the bundled fonts are:

COMFORTAA
FINGER_PAINT
QUICK_SAND

Regards, Dean.

**Comment by rajam1215** [comment]
Hello @Binary-Finery 
 
Thanks for reply, i have my solution with this answer, if i have some issue, then i will come back to you.
while the time i close that issue.

Regards, Bishal Malick.
